version: '3.8'

services:
  nginx:
    image: {{ env.NGINX_IMAGE }}
    ports:
      - '80:80'
    restart: always
    depends_on:
      - frontend
      - backend
  
  frontend:
    image: {{ env.FRONTEND_IMAGE }}
    container_name: frontend
    ports:
      - '3001:3000'
    restart: always

  backend:
    image: {{ env.BACKEND_IMAGE }}
    container_name: backend
    ports:
      - '3002:3000'
    restart: always
