name: CI

env:
  FRONTEND_IMAGE: cr.yandex/crpqppq44fvldj2f1brc/frontend:${{ github.sha }}
  BACKEND_IMAGE: cr.yandex/crpqppq44fvldj2f1brc/backend:${{ github.sha }}
  NGINX_IMAGE: cr.yandex/crpqppq44fvldj2f1brc/nginx:${{ github.sha }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      # - name: Build, tag, and push image to Yandex Cloud Container Registry
      #   env:
      #     CR_REGISTRY: crp00000000000000000
      #     CR_REPOSITORY: my-cr-repo
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
      #     docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
