name: CI

env:
  FRONTEND_IMAGE: cr.yandex/${{ vars.CR_REGISTRY }}/frontend:${{ github.sha }}
  BACKEND_IMAGE: cr.yandex/${{ vars.CR_REGISTRY }}/backend:${{ github.sha }}
  NGINX_IMAGE: cr.yandex/${{ vars.CR_REGISTRY }}/nginx:${{ github.sha }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry [Nginx]
        run: |
          docker build -t ${{ env.NGINX_IMAGE }} -f ./nginx/Dockerfile ./nginx
          docker push ${{ env.NGINX_IMAGE }}
